### ISSUE TITLE
code of attacking methods

### ISSUE THREAD

**Issue by rsindper** [AmIAttribute/AmI#3]
Many thanks for sharing the code. Is it possible to also share the code of those attack methods, especially the glass the patch attack? thanks in advance!

**Comment by Gwinhen** [comment]
Thanks for your interest in our project.

- The untargeted attacks are from [CleverHans](https://github.com/cleverhans-lab/cleverhans).
- The targeted attacks are from [C&W official repo](https://github.com/carlini/nn_robust_attacks).
- The patch and the glass attacks are adapted from [TrojanNN](https://github.com/PurduePAML/TrojanNN). Specifically, we modify the code in [act_max.tvd.center_part.py](https://github.com/PurduePAML/TrojanNN/blob/master/code/gen_trigger/act_max.tvd.center_part.py) by providing the mask for the patch/glass. We manually annotate the location of the glass to be stamped on the face images.
